"""
Multilingual support (English / Tamil / Hindi).

Two layers:
  1. UI text: page headings, key labels and the follow-up questions come from
     the STRINGS table below (works offline, no API needed).
  2. AI output: Echo's replies, insights and photo/report summaries are
     generated by Gemini in the selected language (see llm.py).

Note: the left-hand page navigation labels come from the page filenames and
stay in English (a Streamlit multipage limitation).
"""
import streamlit as st

LANGS = {"English": "en", "தமிழ் (Tamil)": "ta", "हिन्दी (Hindi)": "hi"}
LANG_NAMES = {"en": "English", "ta": "Tamil", "hi": "Hindi"}

STRINGS = {
    "dashboard_title": {"en": "Your Health Dashboard", "ta": "உங்கள் ஆரோக்கிய டேஷ்போர்டு", "hi": "आपका स्वास्थ्य डैशबोर्ड"},
    "welcome_back": {"en": "Welcome back", "ta": "மீண்டும் வருக", "hi": "वापसी पर स्वागत है"},
    "story_title": {"en": "My Story", "ta": "என் கதை", "hi": "मेरी कहानी"},
    "story_sub": {"en": "Describe what you're experiencing in your own words.",
                  "ta": "நீங்கள் அனுபவிப்பதை உங்கள் சொந்த வார்த்தைகளில் விவரிக்கவும்.",
                  "hi": "आप जो अनुभव कर रहे हैं उसे अपने शब्दों में बताइए।"},
    "save_entry": {"en": "Save entry", "ta": "பதிவைச் சேமி", "hi": "प्रविष्टि सहेजें"},
    "tracker_title": {"en": "Daily Health Tracker", "ta": "தினசரி ஆரோக்கிய கண்காணிப்பு", "hi": "दैनिक स्वास्थ्य ट्रैकर"},
    "save_checkin": {"en": "Save today's check-in", "ta": "இன்றைய பதிவைச் சேமி", "hi": "आज की जाँच सहेजें"},
    "chat_title": {"en": "Echo, Your AI Companion", "ta": "எக்கோ, உங்கள் AI துணை", "hi": "इको, आपका AI साथी"},
    "chat_placeholder": {"en": "Ask Echo about your symptoms, tracker trends, or reports...",
                         "ta": "உங்கள் அறிகுறிகள், பதிவுகள் பற்றி எக்கோவிடம் கேளுங்கள்...",
                         "hi": "अपने लक्षणों, ट्रैकर या रिपोर्ट के बारे में इको से पूछें..."},
    "doctors_title": {"en": "Find Doctors, District by District", "ta": "மாவட்ட வாரியாக மருத்துவரைத் தேடுங்கள்", "hi": "ज़िलेवार डॉक्टर खोजें"},
    "district": {"en": "District", "ta": "மாவட்டம்", "hi": "ज़िला"},
    "specialty": {"en": "Specialty", "ta": "சிறப்புப் பிரிவு", "hi": "विशेषज्ञता"},
    "appointments_title": {"en": "Appointments", "ta": "சந்திப்புகள்", "hi": "अपॉइंटमेंट"},
    "medicines_title": {"en": "Medicine Tracker", "ta": "மருந்து கண்காணிப்பு", "hi": "दवा ट्रैकर"},
    "vitals_title": {"en": "Vitals: BMI, Blood Pressure, Sugar", "ta": "உடல்நிலை: BMI, இரத்த அழுத்தம், சர்க்கரை", "hi": "वाइटल्स: BMI, रक्तचाप, शुगर"},
    "language": {"en": "Language", "ta": "மொழி", "hi": "भाषा"},
    "emergency_note": {"en": "In an emergency call 112.", "ta": "அவசரநிலையில் 112 ஐ அழைக்கவும்.", "hi": "आपातकाल में 112 पर कॉल करें।"},
    "not_a_doctor": {"en": "Echo is not a doctor and cannot diagnose you.",
                     "ta": "எக்கோ மருத்துவர் அல்ல; நோயைக் கண்டறிய முடியாது.",
                     "hi": "इको डॉक्टर नहीं है और निदान नहीं कर सकता।"},
    "followup_intro": {"en": "To understand this better, could you tell me:",
                       "ta": "இதைச் சிறப்பாகப் புரிந்துகொள்ள, தயவுசெய்து சொல்லுங்கள்:",
                       "hi": "इसे बेहतर समझने के लिए कृपया बताइए:"},
    "q_duration": {"en": "How long has this been going on?", "ta": "இது எவ்வளவு காலமாக இருக்கிறது?", "hi": "यह कब से हो रहा है?"},
    "q_severity": {"en": "How severe is it, from 1 (mild) to 10 (worst)?",
                   "ta": "இது எவ்வளவு தீவிரம்? 1 (லேசானது) முதல் 10 (மிக மோசம்) வரை?",
                   "hi": "यह कितना गंभीर है, 1 (हल्का) से 10 (सबसे ज़्यादा) तक?"},
    "q_trigger": {"en": "Does anything trigger it or make it better or worse (food, activity, time of day)?",
                  "ta": "ஏதாவது இதைத் தூண்டுகிறதா அல்லது கூட்டுகிறதா/குறைக்கிறதா (உணவு, செயல்பாடு, நேரம்)?",
                  "hi": "क्या कुछ इसे बढ़ाता या घटाता है (खाना, गतिविधि, दिन का समय)?"},
    "record_voice": {"en": "🎙️ Or record your symptoms", "ta": "🎙️ அல்லது உங்கள் அறிகுறிகளைப் பதிவு செய்யுங்கள்", "hi": "🎙️ या अपने लक्षण बोलकर रिकॉर्ड करें"},
}


def get_lang() -> str:
    return st.session_state.get("lang", "en")


def lang_name() -> str:
    return LANG_NAMES.get(get_lang(), "English")


def t(key: str, lang: str | None = None) -> str:
    lang = lang or get_lang()
    entry = STRINGS.get(key, {})
    return entry.get(lang) or entry.get("en") or key
