import streamlit as st
import db, auth, styles, rag, llm

st.set_page_config(page_title="AI Insights — EchoCare", page_icon="✨", layout="wide")
auth.require_login()
styles.inject()
user = auth.current_user()

styles.hero("AI Health Insights", "Powered by LE-RAG: a theme is only surfaced once there's "
                                   "real corroborating evidence — never a guess dressed up as an insight.")

if not llm.gemini_configured():
    st.warning("Gemini isn't configured — insight text will show as unavailable until "
               "`GOOGLE_API_KEY` is set in Streamlit secrets. Evidence is still recorded normally.")

if st.button("✨ Generate new insights", type="primary"):
    with st.spinner("Retrieving evidence, checking sufficiency gates, generating..."):
        new_insights = rag.generate_insights(user["id"], llm.gemini_generate)
        for ins in new_insights:
            db.insert_insight(user["id"], ins)
        generation_errors = sorted({ins["generation_error"] for ins in new_insights
                                    if ins.get("generation_error")})
    if generation_errors:
        st.error("Gemini could not generate insight text: " + "; ".join(generation_errors))
    else:
        st.success(f"Generated {len(new_insights)} insight(s).")

st.divider()
insights = db.get_insights(user["id"])
if not insights:
    st.info("No insights yet. Add a story entry, complete your survey, or log a few tracker "
            "days — themes need at least 2 occurrences across 2+ source types before an insight is generated.")
else:
    cols = st.columns(2)
    for i, ins in enumerate(insights):
        with cols[i % 2]:
            kind = ins["confidence_label"]
            st.markdown(f"""
                <div class="tuf-card">
                    <div style="display:flex;justify-content:space-between;align-items:center;">
                        <span style="color:var(--muted);font-size:.75rem;text-transform:uppercase;">{ins['theme'].replace('_',' ')}</span>
                        {styles.badge(f"{kind} · {round(ins['confidence']*100)}%", kind)}
                    </div>
                    <p style="margin:.6rem 0;">{ins['text']}</p>
                    <p style="color:var(--muted);font-size:.78rem;">{ins['evidence_summary']}</p>
                    <p class="tuf-disclaimer">This is not a diagnosis — a discussion point for your clinician, based only on the evidence shown. Generated by: {ins['generated_by']}</p>
                </div>
            """, unsafe_allow_html=True)
